"""initial schema

Revision ID: 68802b4a7653
Revises: 
Create Date: 2026-09-13 08:08:28.128865
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '68802b4a7653'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('chore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('recurrence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval_n', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('assignment_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fixed_user_id', sa.Integer(), nullable=True),
    sa.Column('rotation_position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixed_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chore_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('skipped_by_user_id', sa.Integer(), nullable=True),
    sa.Column('skip_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['chore_id'], ['chore.id'], ),
    sa.ForeignKeyConstraint(['skipped_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chore_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chore_instance_chore_id'), ['chore_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_instance_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_instance_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_instance_status'), ['status'], unique=False)
        batch_op.create_index('uq_instance_one_open', ['chore_id'], unique=True, sqlite_where=sa.text("status = 'pending'"))

    op.create_table('chore_rotation_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chore_id'], ['chore.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chore_id', 'user_id', name='uq_roster_chore_user')
    )
    with op.batch_alter_table('chore_rotation_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chore_rotation_member_chore_id'), ['chore_id'], unique=False)

    op.create_table('completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chore_instance_id', sa.Integer(), nullable=True),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['chore_id'], ['chore.id'], ),
    sa.ForeignKeyConstraint(['chore_instance_id'], ['chore_instance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chore_instance_id')
    )
    with op.batch_alter_table('completion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completion_chore_id'), ['chore_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_completion_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_completion_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completion_user_id'))
        batch_op.drop_index(batch_op.f('ix_completion_completed_at'))
        batch_op.drop_index(batch_op.f('ix_completion_chore_id'))

    op.drop_table('completion')
    with op.batch_alter_table('chore_rotation_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chore_rotation_member_chore_id'))

    op.drop_table('chore_rotation_member')
    with op.batch_alter_table('chore_instance', schema=None) as batch_op:
        batch_op.drop_index('uq_instance_one_open', sqlite_where=sa.text("status = 'pending'"))
        batch_op.drop_index(batch_op.f('ix_chore_instance_status'))
        batch_op.drop_index(batch_op.f('ix_chore_instance_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_chore_instance_due_date'))
        batch_op.drop_index(batch_op.f('ix_chore_instance_chore_id'))

    op.drop_table('chore_instance')
    op.drop_table('chore')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('setting')
    # ### end Alembic commands ###
